In [71]:
import numpy as np
new_array=np.array([1,2,3])
f=new_array.tolist()
print (f)


[1, 2, 3]
<class 'list'>


In [74]:
array=np.random.randint(5,15,size=(4,4))
print(array)
np.trace(array)

[[ 8 11  9  8]
 [12  5  9 11]
 [13 14  8  5]
 [10 11  6  5]]


26

In [77]:
arr=np.random.randint(4,10,size=(2,4))

print(arr)
print ("-")
print ("-")
print ("-")
print(arr[8<arr])

[[9 4 6 7]
 [8 9 8 6]]
-
-
-
[9 9]


In [26]:
import numpy as np
A=np.array([[2,2],[3,4]])
B=np.array([[2,2],[2,2]])
t=A.shape
C=np.zeros((int(t[0]),int(t[1])))
for i in range(t[0]):
    for j in range(t[1]):
        C[i,j]=A[i,j]+B[i,j]
        
print(C)       
        
    
    
    

[[4. 4.]
 [5. 6.]]


In [43]:
import statistics as st
import numpy as np
arr1=np.random.randint(4,19,size=(4,4))
Mean=st.mean(arr1[:,-1])
t=arr1.shape
I=np.zeros((int(4),int(4)))
list_arr=[]
for i in arr1:
    Mean=st.mean(i)
    I=Mean-i
    list_arr.append(I)
arr2=np.array(list_arr)
print(arr1)
print ("-")
print ("-")
print ("-")
print ("-")
print (arr2)
    
    
    

[[18 13  9 15]
 [16  7  7  5]
 [11  4  9 14]
 [13 10  6  5]]
-
-
-
-
[[-5  0  4 -2]
 [-8  1  1  3]
 [-2  5  0 -5]
 [-5 -2  2  3]]
