In [71]:
import numpy as np
new_array=np.array([1,2,3])
f=new_array.tolist()
print (f)


[1, 2, 3]
<class 'list'>


In [74]:
array=np.random.randint(5,15,size=(4,4))
print(array)
np.trace(array)

[[ 8 11  9  8]
 [12  5  9 11]
 [13 14  8  5]
 [10 11  6  5]]


26

In [77]:
arr=np.random.randint(4,10,size=(2,4))

print(arr)
print ("-")
print ("-")
print ("-")
print(arr[8<arr])

[[9 4 6 7]
 [8 9 8 6]]
-
-
-
[9 9]


In [80]:
A=np.array([[2,2],[3,4]])
B=np.array([[2,2]],[[2,2]])
t=A.shape
t1=B.shape
for i in range(t[0]):
for j in range(t[1]):
    
    
    

SyntaxError: invalid syntax (<ipython-input-80-9aa1157c6af6>, line 4)

In [9]:
import statistics as st
import numpy as np
arr1=np.random.randint(4,19,size=(4,4))
print(arr1[:,0])
Mean=st.mean(arr1[:,-1])
t=arr1.shape
for i in range(t[0]):
    Mean=st.mean(arr1[:,-1])
    s=Mean-Mean
print(arr1)    
print(s)
    
    
    

[15  9 14 17]
[[15 15  6  8]
 [ 9  8 18 18]
 [14 14 13 17]
 [17 13  8 16]]
0


(4, 4)